server:
  servlet:
    context-path: /EmployeePortalWithSpringBoot
spring:
  datasource: 
    url: jdbc:mysql://localhost/employee_portal
    username: root
    password: 1025
    driver-class-name : com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource